apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # NOTE: We want the configmaps to be created/updated before anything else
    # because even pre-start jobs like migrations and collectstatic depend on it
    "helm.sh/hook-weight": "-3"
data:
  DJANGO_DEBUG: "{{ .Values.appConfig.djangoDebug }}"
  DJANGO_SETTINGS_MODULE: "{{ .Values.appConfig.djangoSettingsModule }}"
  DJANGO_DATABASE_URL: "{{ .Values.appConfig.djangoDatabaseUrl }}"
  DJANGO_SECRET_KEY: "{{ .Values.appConfig.djangoSecretKey }}"
  DJANGO_HOSTNAME: "{{ .Values.appConfig.djangoHostname }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.appConfig.djangoAllowedHosts }}"
  DJANGO_CSRF_COOKIE_SECURE: "{{ .Values.appConfig.csrfCookieSecure }}"
  DJANGO_CSRF_TRUSTED_ORIGINS: "{{ .Values.appConfig.csrfTrustedOrigins }}"
  AWS_STORAGE_BUCKET_NAME: "{{ .Values.appConfig.awsStorageBucketName }}"
  AWS_S3_REGION_NAME: "{{ .Values.appConfig.awsS3RegionName }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.appConfig.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.appConfig.awsSecretAccessKey }}"
