apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-s3-bucket
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.appConfig.awsStorageBucketName }}.s3.{{ .Values.appConfig.awsS3RegionName }}.scw.cloud
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
