appConfig:
  djangoDebug: false
  djangoAllowedHosts: "hellok8s-django.deni.cloud"
  djangoHostname: hellok8s-django.deni.cloud
  djangoSettingsModule: "project.settings.prod"
  csrfCookieSecure: true
  csrfTrustedOrigins: "https://hellok8s-django.deni.cloud"
  gunicornProcesses: 2
  awsS3RegionName: fr-par

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  hosts:
    - host: hellok8s-django.deni.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hellok8s-django
      hosts:
        - hellok8s-django.deni.cloud
