name: docker
permissions:
  id-token: write # Important for at least docker gha cache
  contents: read
on:
  workflow_call:
jobs:
  docker:
    runs-on: ubuntu-latest
    name: docker
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3.1.0
      # - name: Expose actions cache variables
      #   uses: actions/github-script@v7.0.1
      #   with:
      #     script: |
      #       core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
      #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
      # NOTE: use this is using Amazon ECR
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4.0.2
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     aws-region: us-east-1
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2.0.1
      #   id: login-ecr
      #
      # NOTE: use this if pushing to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set SHORT_SHA
        run: |
          # debug - useful for quickly figuring out the image tag of a given pipeline
          echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)"
          echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build Tailwind CSS
        run: yarn build-css
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Build docker image
        shell: bash
        env:
          IMAGE_TAG: "sha-${{ env.SHORT_SHA }}"
          CACHE_ARGS: "--cache-to type=gha,mode=max --cache-from type=gha"
        run: make build-docker-image
      - name: Push docker image
        if: github.ref == 'refs/heads/main'
        shell: bash
        env:
          IMAGE_TAG: "sha-${{ env.SHORT_SHA }}"
        run: make push-docker-image
